### DISCUSSION TITLE
how to change the height of map

### DISCUSSION THREAD

**Discussion by HaveF** [rclement/datasette-dashboards#151] [Q&A]
I can't set the height of the map, even I set 3 lines in layout.

```
- [map1, map1, map1, map1, map1, map1]
- [map1, map1, map1, map1, map1, map1]
- [map1, map1, map1, map1, map1, map1]
```

have any suggestion?

**Comment by HaveF** [comment]
`height` also not works.

**Reply by rclement** [reply]
Where are you specify the `height` attribute?

**Reply by HaveF** [reply]
I'm just experimenting with if there are any hidden properties 😂

**Comment by rclement** [comment]
Indeed, currently the grid implementation makes use of:
- `grid-template-areas` + `grid-area` to position the grid/matrix of charts
- `grid-auto-columns: minmax(100px, 1fr);` to specify the min/max width of columns

So by default a row will have a height of `1fr` (which seems to be defaulting to 200px). We could use `grid-auto-rows` to try something smart and/or configurable to specify row height but I cannot grasp a good solution for now. Happy to get some propositions if any.

Please note these CSS Grid constraints apply to all chart types, not only maps.

Nevertheless, if you want to checkout the chart in full height and full width, simply click on the chart title to display the chart page!

**Reply by HaveF** [reply]
I was wondering, wouldn't it be better to add a css property for each component?

```yaml
events-count:
        title: Total number of events
        db: jobs
        query: SELECT count(*) as count FROM events
        library: metric
        css: {height: 500px; background: 'yellow'}
        display:
          field: count
          prefix:
          suffix:
```
