### ISSUE TITLE
Allow markdown configuration at chart level

### ISSUE THREAD

**Issue by shaib** [rclement/datasette-dashboards#288]
Current documentation (readme.md) [says](https://github.com/rclement/datasette-dashboards/blob/4e7a7d2f9148792b226b41b8f3ccc9571483baea/README.md?plain=1#L188):
- Markdown rendering is done by [datasette-render-markdown](https://datasette.io/plugins/datasette-render-markdown)
- To configure Markdown rendering, extensions can be enabled in [metadata](https://datasette.io/plugins/datasette-render-markdown#user-content-markdown-extensions)

But this is not really the case -- when rendering a markdown chart, the extensions (as well as extra tags, and no extra attrs) are [hard-coded into the template](https://github.com/rclement/datasette-dashboards/blob/4e7a7d2f9148792b226b41b8f3ccc9571483baea/datasette_dashboards/templates/dashboard_view.html#L127)

In fact, datesette-render-markdown itself only takes extensions etc from its configuration when it renders a database value as markdown. When the `render_markdown()` hook is used, it expects the values to be passed in explicitly.

I suggest that these values be allowed to be set on the chart itself, i.e.

```
     ...
      charts:
        analysis-note:
          library: markdown
          extensions:
            - extra
            - tables
          extra_tags: ["table", "thead", "tr", "th", "td", "tbody"]
          extra_attrs:
            tr:
              - class
              - name
          display: |-
            # Analysis notes
            > A quick rundown of events statistics and KPIs
            | col1     | col2  |
            +----------+-------+
            | whatever | what2 |
```

**Comment by rclement** [comment]
Good catch @shaib!
Indeed I may have overlooked this feature at the time, thanks for digging in.
Regarding your proposal, the only thing I'm not sure about is having the keys `extensions`, `extra_tags`, `extra_attrs` at the chart root level, as these are kind of "settings" for this type of component.

Maybe something along the lines of the following would be more explicit and easier to maintain and extend for other types of charts?

```yaml
     ...
      charts:
        analysis-note:
          library: markdown
          settings:
            extensions:
              - extra
              - tables
            extra_tags: ["table", "thead", "tr", "th", "td", "tbody"]
            extra_attrs:
              tr:
                - class
                - name
          display: |-
            # Analysis notes
            > A quick rundown of events statistics and KPIs
            | col1     | col2  |
            +----------+-------+
            | whatever | what2 |
```
