### ISSUE TITLE
List of values for filters

### ISSUE THREAD

**Issue by CharlesNepote** [rclement/datasette-dashboards#51]
List of values would be great for filters.

I hope the following example speaks by itself.
```yml
      filters:
        country:
          name: Country
          type: list
          values: world,be,es,fr,uk,us
        language:
          name: Language
          type: query
          # it has to be a unique column
          sql: select distinct language from this_table;
```
