### ISSUE TITLE
Dashboard filter default value is not applied automatically

### ISSUE THREAD

**Issue by rclement** [rclement/datasette-dashboards#52]
When specifying a default value for a filter, it is not applied automatically when opening the dashboard.

As done by Metabase (and others), when accessing a dashboard without query parameters, the request should be redirected to the same dashboard but with query arguments filled with filters default values.

Example:

Using this configuration:

```yaml
plugins:
  datasette-dashboards:
    job-offers-stats:
      title: Job offers statistics
      description: Gather metrics about job offers
      layout:
        - [analysis-note, offers-day, offers-day, offers-count]
        - [analysis-note, offers-source, offers-day-source, offers-region]
      filters:
        date_start:
          name: Date Start
          type: date
          default: '2021-01-01'
        date_end:
          name: Date End
          type: date
```

When accessing `/-/dashboards/job-dashboard`, it should be redirected to `/-/dashboards/job-dashboard?date_start=2021-01-01`.
