### ISSUE TITLE
Add multiple select filter

### ISSUE THREAD

**Issue by rclement** [rclement/datasette-dashboards#54]
Add an option to select filter type allowing to select multiple values.

Example:

```yaml
...
      filters:
        source:
          name: Source
          type: select
          multiple: true
          options: [Source 1, Source 2, Source 3]
          default: [Source1, Source 2]
...
```

2 potential implementation:
- HTML `select` tags can specify a `multiple` attribute allowing multiple values selection of options: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple
- HTML `checkbox` input using a `fieldset`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox
