### ISSUE TITLE
Dynamic values for select filter type

### ISSUE THREAD

**Issue by rclement** [rclement/datasette-dashboards#59]
It would be great if values for the `select` filter type could be dynamically filled with the results from a query.

Sample configuration:
```yaml
...
      filters:
        source:
          name: Source
          type: select
          db: test
          query: select distinct name from sources order by name asc
...
```
