### ISSUE TITLE
Allow dashboards to enter fullscreen

### ISSUE THREAD

**Issue by rclement** [rclement/datasette-dashboards#77]
It would be nice for the dashboards to be allowed to toggle a fullscreen mode at the click of a button.

Here is a snippet to toggle fullscreen mode:

```html
<button
  onclick="document.fullscreenElement
    ? document.exitFullscreen()
    : document.body.requestFullscreen()
  "
>
  Toggle Fullscreen
</button>
```

Instead of `document.body` it is more advisable to select a sub-section of the page to be made fullscreen: for instance, it could be only the central dashboarding part (title, description, filters, chart grid) without header nor footer.

**Comment by rclement** [comment]
Also the background color is lost when entering fullscreen and must be specified using the following selectors:
```css
:fullscreen, ::backdrop {
  background-color: #F8FAFB;
}
```

**Comment by rclement** [comment]
It would be useful to introduce a global dashboard setting configuration, such as:

```yaml
dashboards:
  my-dashboard:
    settings:
      allow_fullscreen: true
```
